apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-search-service
  namespace: nimble-platform
  labels:
    app: nimble-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-search-service
  template:
    metadata:
      labels:
        app: catalog-search-service
    spec:
      containers:
      - name: catalog-search-service
        image: 'rannybal2024/catalog-search-service:IMAGE_TAG'
        ports:
        - containerPort: 8090
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: 'productive'
          - name: CONFIG_SERVER_URI
            value: 'http://config-server:8888'
          - name: CONFIG_SERVER_FAILFAST
            value: "true"
          - name: DISCOVERY_ENABLED
            value: "true"
          - name: DISCOVERY_SERVER_URI
            value: "http://service-discovery:8761"
          - name: DISCOVERY_PREFER_IP
            value: "false"
          - name: MARMOTTA_URL
            value: 'http://marmotta:8080'
          - name: LANGUAGE_LABEL
            value: 'http://www.w3.org/2004/02/skos/core#prefLabel'
          - name: USE_SOLR_INDEX
            value: 'true'
          - name: PORT
            value: '8090'