kind: Service
metadata:
  name: catalog-search-service
  labels:
    app: nimble-platform
    name: catalog-search-service
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8090
      targetPort: 8090
  selector:
    app: nimble-platform
    name: catalog-search-service